# .goreleaser.yml
brews:
  - name: awls
    respository:
      owner: danpilch
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
    description: "Lookup EC2 information in the terminal"
    license: "MIT"
