# .goreleaser.yml
version: 2
brews:
  - name: awls
    repository:
      owner: danpilch
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    description: "Lookup EC2 information in the terminal"
    license: "MIT"
