# .goreleaser.yml
brews:
  - 
    name: awls
    tap:
      owner: danpilch
      name: homebrew-awls
      token: "{{ .secret.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    description: "Lookup EC2 information in the terminal"
    license: "MIT"
